apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

dashboards:
  - name: Infrastructure Overview
    folder: NisargHunter
    type: file
    options:
      path: /etc/grafana/provisioning/dashboards

  - name: AI Metrics
    folder: NisargHunter
    type: file
    options:
      path: /etc/grafana/provisioning/dashboards

  - name: Worker Health
    folder: NisargHunter
    type: file
    options:
      path: /etc/grafana/provisioning/dashboards

  - name: Websocket Health
    folder: NisargHunter
    type: file
    options:
      path: /etc/grafana/provisioning/dashboards
