apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nisarghunter-backend-pdb
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nisarghunter
      component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nisarghunter-worker-pdb
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nisarghunter
      component: workers
