"""add_report_model.

Revision ID: 0b39c345405e
Revises: 0009_plugin_marketplace_extensions
Create Date: 2026-05-26 18:04:22.707554
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b39c345405e'
down_revision = '0009_plugin_marketplace_extensions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_programs_handle'), 'programs', ['handle'], unique=False)
    op.create_index('ix_report_drafts_finding_platform', 'report_drafts', ['finding_id', 'platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_drafts_finding_platform', table_name='report_drafts')
    op.drop_index(op.f('ix_programs_handle'), table_name='programs')
    # ### end Alembic commands ###
