"""add_report_improvements.

Revision ID: 91c8a126e68a
Revises: 0906c55c8c31
Create Date: 2026-05-27 12:16:52.975293
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c8a126e68a'
down_revision = '0906c55c8c31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('improvements', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'improvements')
    # ### end Alembic commands ###
