"""
Change Event model: immutable audit record of detected infrastructure drift.

Design principles:
- IMMUTABLE: change events are write-once historical facts.
- AUDITABILITY: every detected change is traceable back to its source scan
  and the two snapshots it was derived from.
- SEVERITY-AWARE: change events carry business-impact severity for triage.
- WORKSPACE-ISOLATED: scoped to organization for strict multi-tenancy.
"""
from __future__ import annotations

from enum import Enum
from uuid import UUID

from sqlalchemy import (
    DateTime,
    Float,
    ForeignKey,
    Index,
    JSON,
    String,
    Text,
    Enum as SQLEnum,
    func,
)
from sqlalchemy import Uuid as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.database.base import Base, UUIDMixin


class ChangeType(str, Enum):
    """Taxonomy of infrastructure changes the system can detect."""

    # Asset lifecycle
    NEW_ASSET = "new_asset"             # Host appeared for the first time
    REMOVED_ASSET = "removed_asset"     # Host stopped responding / dropped from scope

    # Endpoint lifecycle
    NEW_ENDPOINT = "new_endpoint"           # New URL/path discovered
    REMOVED_ENDPOINT = "removed_endpoint"   # Endpoint no longer accessible

    # Technology drift
    TECHNOLOGY_CHANGE = "technology_change"     # Version bump or framework swap

    # Exposure evolution
    EXPOSURE_CHANGE = "exposure_change"     # Exposure state / severity changed
    NEW_EXPOSURE = "new_exposure"           # Brand-new exposure detected
    RESOLVED_EXPOSURE = "resolved_exposure" # Exposure remediated

    # Risk evolution
    RISK_CHANGE = "risk_change"             # Asset risk score shifted significantly


class ChangeSeverity(str, Enum):
    """Business-impact severity of a detected change."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class ChangeEvent(Base, UUIDMixin):
    """
    Immutable audit record of a single detected infrastructure change.

    Created by the change detection service when diffing two successive
    snapshots.  Never modified after initial insert.

    Columns
    -------
    organization_id : UUID
        Workspace isolation; all queries MUST filter on this.
    asset_id : UUID | None
        The affected asset, if the change is asset-scoped.
    program_id : UUID | None
        Program scope, if applicable.
    change_type : ChangeType
        Categorised change taxonomy.
    previous_value : dict | None
        Serialised representation of the state BEFORE the change.
    new_value : dict | None
        Serialised representation of the state AFTER the change.
    severity : ChangeSeverity
        Business-impact severity assigned during detection.
    change_score : float
        Numeric severity score [0–100] for trend analytics.
    description : str | None
        Human-readable narrative generated by the detection service.
    source_snapshot_id : UUID | None
        The "before" snapshot used in the diff.
    target_snapshot_id : UUID | None
        The "after" snapshot used in the diff.
    detected_by_scan_id : UUID | None
        The scan that triggered this change detection run.
    detected_at : datetime
        Server-side immutable timestamp.
    """

    __tablename__ = "change_events"

    # ── Workspace isolation ────────────────────────────────────────────────
    organization_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    program_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("programs.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )

    # ── Subject of the change ─────────────────────────────────────────────
    asset_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("assets.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # ── Change classification ──────────────────────────────────────────────
    change_type: Mapped[str] = mapped_column(
        SQLEnum(ChangeType),
        nullable=False,
        index=True,
    )
    severity: Mapped[str] = mapped_column(
        SQLEnum(ChangeSeverity),
        nullable=False,
        default=ChangeSeverity.INFO,
        index=True,
    )
    change_score: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
    )  # 0–100 numeric severity for analytics

    # ── Diff payload ──────────────────────────────────────────────────────
    previous_value: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    new_value: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # ── Human-readable context ────────────────────────────────────────────
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Provenance / auditability ─────────────────────────────────────────
    source_snapshot_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("recon_snapshots.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    target_snapshot_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("recon_snapshots.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    detected_by_scan_id: Mapped[UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("scans.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # ── Immutable detection timestamp ─────────────────────────────────────
    detected_at: Mapped[object] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    # ── Relationships (read-only navigation) ──────────────────────────────
    asset = relationship(
        "Asset",
        foreign_keys=[asset_id],
        lazy="select",
    )
    source_snapshot = relationship(
        "ReconSnapshot",
        foreign_keys=[source_snapshot_id],
        lazy="select",
    )
    target_snapshot = relationship(
        "ReconSnapshot",
        foreign_keys=[target_snapshot_id],
        lazy="select",
    )

    # ── Composite indexes ─────────────────────────────────────────────────
    __table_args__ = (
        Index("ix_change_evt_org_type_time", "organization_id", "change_type", "detected_at"),
        Index("ix_change_evt_org_severity", "organization_id", "severity", "detected_at"),
        Index("ix_change_evt_asset_time", "asset_id", "detected_at"),
        Index("ix_change_evt_org_prog", "organization_id", "program_id", "detected_at"),
    )

    def __repr__(self) -> str:
        return (
            f"<ChangeEvent id={self.id} type={self.change_type} "
            f"severity={self.severity} org={self.organization_id}>"
        )
